---
# tasks file for netscaler_lb_vip_mgmt
    - name: Enable load balancing vserver bound to services
      delegate_to: localhost
      citrix_adc_lb_vserver:
         nsip: "{{ nsip }}"
         nitro_user: "{{ nitro_user }}"
         nitro_pass: "{{ nitro_pass }}"
         validate_certs: no
         disabled: false
         save_config: true
         name: "{{ item|split('-')|first }}"
         clttimeout: "{{ wait_time }}"
      when: >-
           ( 'ENABLE' in status )
      with_items: "{{ lb_vserver }}"

    - name: Disable load balancing vserver bound to services
      delegate_to: localhost
      citrix_adc_lb_vserver:
         nsip: "{{ nsip }}"
         nitro_user: "{{ nitro_user }}"
         nitro_pass: "{{ nitro_pass }}"
         validate_certs: no
         disabled: true
         save_config: true
         name: "{{ item|split('-')|first }}"
         clttimeout: "{{ wait_time }}"
      when: >-
           ( 'DISABLE' in status )
      with_items: "{{ lb_vserver }}"

